# An L2TP/IPSec VPN server
version: '3.7'
services:
  vpn:
    image: hwdsl2/ipsec-vpn-server
    environment:
      TZ: America/New_York
    env_file:
      # Usernames and passwords
      - vpn.env
    volumes:
      - /lib/modules:/lib/modules:ro
    ports:
      - 500:500/udp
      - 4500:4500/udp
    restart: always
    privileged: true
