# Example docker-compose file
# I made this to make creating new services faster
version: '3.7'
services:
  :
    image:
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/New_York
    volumes:
      - ./data/:/
    labels:
      caddy.address: '.home.wingysam.xyz'
      caddy.targetport: 
      caddy.proxy.transparent: ''
    restart: always
