# Today I Found Interesting - https://tifi.home.wingysam.xyz
version: '3.7'
services:
  ghost:
    image: ghost:3-alpine
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/New_York
      url: https://tifi.home.wingysam.xyz
    volumes:
      - ./data/content:/var/lib/ghost/content
    labels:
      caddy.address: 'tifi.home.wingysam.xyz'
      caddy.targetport: 2368
      caddy.proxy.transparent: ''
    restart: always

  ackee:
    image: electerious/ackee
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/New_York
      WAIT_HOSTS: ackeemongo:27017
      ACKEE_MONGODB: mongodb://ackeemongo:27017/ackee
    env_file:
      # ACKEE_USERNAME and ACKEE_PASSWORD
      - ackee.env
    labels:
      caddy.address: 'ackee.tifi.home.wingysam.xyz'
      caddy.targetport: 3000
      caddy.proxy.transparent: ''
      caddy.cors.origin: 'https://tifi.home.wingysam.xyz'
      caddy.cors.methods: '*'
      caddy.cors.allowed_headers: '*'
    restart: always
  ackeemongo:
    image: mongo
    restart: always
    volumes:
      - ./data/ackeemongo:/data/db
