# ArchiveTeam Warrior is used to help the distributed archiving of things
# https://www.archiveteam.org/index.php?title=ArchiveTeam_Warrior
version: '3.7'
services:
  URLTeam:
    image: archiveteam/warrior-dockerfile
    environment:
      TZ: America/New_York
      DOWNLOADER: Wingy
      SELECTED_PROJECT: urlteam2
      CONCURRENT_ITEMS: 6
    ports:
      - 8001
    restart: always
  Auto:
    image: archiveteam/warrior-dockerfile
    environment:
      TZ: America/New_York
      DOWNLOADER: Wingy
      SELECTED_PROJECT: auto
      CONCURRENT_ITEMS: 6
    ports:
      - 8001
    restart: always
