# NextCloud is like G Suite sort of but self hosted.
version: '3.7'
services:
  nextcloud:
    image: linuxserver/nextcloud
    depends_on:
      - db
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - ./data/config:/config
      - ./data/files:/data
    labels:
      caddy.address: 'nextcloud.home.wingysam.xyz'
      caddy.targetport: 443
      caddy.targetprotocol: https
      caddy.proxy.insecure_skip_verify: ''
      caddy.proxy.transparent: ''
      caddy.proxy.websocket: ''
    restart: always

  db:
    image: postgres:11
    network_mode: bridge
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud
      POSTGRES_DB: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
