# The Lounge is my IRC client.
version: '3.7'
services:
  thelounge:
    image: thelounge/thelounge:latest
    depends_on:
      - tildetown
    labels:
      caddy.address: thelounge.home.wingysam.xyz
      caddy.targetport: 9000
      caddy.proxy.transparent: ''
      caddy.proxy.websocket: ''
      caddy.cors: ''
    restart: always
    volumes:
      - ./data/thelounge:/var/opt/thelounge
      - /data/Archives/Chat Logs/IRC:/var/opt/thelounge/logs

  # I have a tunnel to the tilde.town IRC server and tilde.chat bridge.
  tildetown:
    image: cryptkiddie2/ssh-forward
    restart: always
    ports:
      # These are for an irc bot that I was running to access ~town and ~chat
      - 6668:6668
      - 6669:6667
    volumes:
      - ./data/tilde.town/ssh:/home/tunnel/.ssh
