# This is a copy of the old v1 docker-compose but modified to have a seed that they wanted.
---
version: "3.6"
services:
  mc:
    image: itzg/minecraft-server
    volumes:
      - ./data:/data
    environment:
      TZ: America/New_York
      EULA: 'TRUE'
      MEMORY: 5G
      TYPE: PAPER
      SEED: 4469121359717752493
      VERSION: 1.15
      BUILD_FROM_SOURCE: 'true'
    labels:
      autoheal: 'true'
    ports:
      - 25565:25565
#       - 25585:25575
    restart: always
 # rclone:
 #   image: rayou/rclone
 #   command: serve ftp /data --user '${FTP_USER}' --pass '${FTP_PASS}' --addr 0.0.0.0:2121 --passive-port 10011-10100 --uid 1000 --gid 1000
 #   volumes:
 #     - ./data:/data
 #   environment:
 #     TZ: America/New_York
 #   ports:
 #     - '2121:2121'
 #     - '10011-10100:10011-10100'
 #   restart: always
