# Christmas Community is a Christmas wishlist app that I made.
# https://gitlab.com/wingysam/christmas-community
version: '3.7'
services:
  wing:
    image: wingysam/christmas-community
    environment:
      TABLE: 'true'
    volumes:
      - ./data/wing:/data
    labels:
      caddy.address: 'christmas-community.home.wingysam.xyz'
      caddy.targetport: 80
      caddy.proxy.transparent: ''
    restart: always
