# Monica is my personal relationship manager. I mostly use it to keep track of borrowed money.
version: '3.7'
services:
  monicahq:
    image: monicahq/monicahq
    depends_on:
      - mysql
    labels:
      caddy.address: monica.home.wingysam.xyz
      caddy.targetport: 80
      caddy.proxy.transparent: ''
    env_file: monica.env
    volumes:
      - ./data/monica:/var/www/monica/storage
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      # These are not secrets because Monica is the only thing that can access mysql.
      MYSQL_ROOT_PASSWORD: sekret_root_password
      MYSQL_DATABASE: monica
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
